# Label configuration for automatic PR labeling
# Format for actions/labeler@v5

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'pom.xml'
      - '**/pom.xml'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/resources/**/*'
      - '**/application.properties'
      - '**/application.yml'
      - '.github/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/test/**/*'
      - '**/*Test.java'
      - '**/*IT.java'

core:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/core/**/*'

repository:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/repository/**/*'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/config/**/*'

mapping:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/core/mapping/**/*'

query:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/repository/query/**/*'

transaction:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/transaction/**/*'

observability:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/observability/**/*'

schema:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/org/springframework/data/orientdb/core/schema/**/*'

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/**/*'
