# Label configuration for automatic PR labeling

documentation:
  - '**/*.md'
  - 'docs/**/*'

dependencies:
  - 'pom.xml'
  - '**/pom.xml'

configuration:
  - 'src/main/resources/**/*'
  - '**/application.properties'
  - '**/application.yml'
  - '.github/**/*'

tests:
  - 'src/test/**/*'
  - '**/*Test.java'
  - '**/*IT.java'

core:
  - 'src/main/java/org/springframework/data/orientdb/core/**/*'

repository:
  - 'src/main/java/org/springframework/data/orientdb/repository/**/*'

config:
  - 'src/main/java/org/springframework/data/orientdb/config/**/*'

mapping:
  - 'src/main/java/org/springframework/data/orientdb/core/mapping/**/*'

query:
  - 'src/main/java/org/springframework/data/orientdb/repository/query/**/*'

transaction:
  - 'src/main/java/org/springframework/data/orientdb/transaction/**/*'

observability:
  - 'src/main/java/org/springframework/data/orientdb/observability/**/*'

schema:
  - 'src/main/java/org/springframework/data/orientdb/core/schema/**/*'

ci/cd:
  - '.github/workflows/**/*'
  - '.github/**/*'

