name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  pr-check:
    name: PR Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Build and Test
      run: mvn clean test -DskipITs
    
    - name: Check code coverage
      run: mvn jacoco:check
      continue-on-error: true
    
    - name: Comment PR with coverage
      if: always()
      uses: madrapps/jacoco-report@v1.7.2
      with:
        paths: target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 70
        min-coverage-changed-files: 70
        title: 'Code Coverage Report'
    
    - name: Check if build passed
      run: |
        if [ -f target/surefire-reports/TEST-*.xml ]; then
          echo "Tests passed!"
        else
          echo "Tests failed!"
          exit 1
        fi

  pr-label:
    name: PR Auto Label
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Label PR based on files changed
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true

  pr-size:
    name: PR Size Check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
    - name: Check PR size
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: '10'
        s_label: 'size/s'
        s_max_size: '100'
        m_label: 'size/m'
        m_max_size: '500'
        l_label: 'size/l'
        l_max_size: '1000'
        xl_label: 'size/xl'
        fail_if_xl: 'false'

